### ISSUE TITLE
Naming hickups

### ISSUE THREAD

**Issue by JensRantil** [bitly/go-hostpool#16]
The package is named `hostpool`. This means that `HostPool*` prefix shouldn't be needed for `HostPoolResponse`. See https://github.com/golang/go/wiki/CodeReviewComments#package-names. Fixing this would be non-backwards compatible change.

**Comment by jehiah** [comment]
While true that there is some stuttering in the naming of this package (it dates back to 2012 when some of these naming patterns were a little less obvious) it's unlike that this package will see a significant revision any time soon when it'd be appropriate to change.

Thanks for opening this issue - it'll be helpful if/when we do breaking changes in the future.
